import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mirko Passoli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Building my portfolio...
        </h1>

        <p className={styles.description}>
          Passoli Mirko
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/Paxol" className={styles.card}>
            <h2>GitHub &rarr;</h2>
            <p>Check my GitHub profile</p>
          </a>

          <a href="mailto:mirko.passoli@gmail.com" className={styles.card}>
            <h2>Get in touch &rarr;</h2>
            <p>Send me an email</p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
